### PR TITLE
Add Standard document for version policy regarding k8s updates

### PR DESCRIPTION
**Pull request by ajfriesen**
Here is my first draft regarding the version policy.

### CODE REVIEW

**Comment by joshmue** [comment]
Nice!

Right now, the record primarily concerns the speed of picking up new Kubernetes releases.

There are also a few other relevant topics, which may end up (a) not standardized, (b) in this record or (c) as a series of records:

## Support of non-current Kubernetes versions / pace of EOL-ing

What older releases is the provider required to support? All non-current "Minor" releases that are still supported upstream? Maybe more or less? Are patch releases treated differently?

## Responsibilities provider vs. customer

Does the provider prepare version upgrades, but the customer triggers the upgrade on their schedule? Perhaps use another model for patch releases?

**Review by garloff — COMMENTED** [review]
Document looks really good to me.
A few minor suggestions:
1.) Please add the DCO (Signed-Off-By) to your commit message, otherwise we can not merge the PR. `git --amend -s` and then force push (`--force-with-lease`) to the branch.
2.) A small section that says that there how long minor versions stay supported is subject to another Standard document. (The comment from Joshua is a good one, of course!)

**Comment by ajfriesen** [comment]
We discussed that we want to create different ADR for the following topics:
- How long do scs compliant providers need to support versions
- Who does the upgrade of the cluster (user of that cluster or the provider or some mixed mode?)

**Review by garloff — DISMISSED** [review]
/lgtm

**Review by garloff — APPROVED** [review]
Looks still good.

**Pull request merged**
