### PR TITLE
Run pre-check cleanup also in GH actions

### PR DESCRIPTION
**Pull request by martinmo**
Even if we want to completely switch to Zuul, it's not clear when this happens and in the meantime there is still plenty of opportunity that this is the reason for failed tests. The fix is rather easy, I just copied and slightly adapted the invocation from `playbooks/pre_cloud.yaml`.

### CODE REVIEW

**Review by mbuechse — APPROVED** [review]
Thanks for taking the initiative!

**Comment by martinmo** [comment]
Please note: I'll merge this on monday, because I fear that this might break something and I don't want to risk this right before the weekend :-)

**Comment by martinmo** [comment]
After having another look, I came to the conclusion that this can't work reliably: the workflows for one cloud can run in parallel, sometimes 4 at the same time (and not only because of the same schedule, they also run after the Docker image was built). Hence, with good timing, the cleanup will interfere with a run. This can be worked around by running the cleanup only for IaaS v4 checks (it is only needed there).

**Comment by mbuechse** [comment]
I guess it would have been better in principle to define a separate cleanup job and make it a prerequisite of the compliance-test job. Since we want to abandon the Github jobs anyway (#672), we may opt to save us this effort.

**Comment by martinmo** [comment]
I agree with both statements, this is why I just used the quick workaround :+1:

**Pull request merged**
