### PR TITLE
#675 - Node to Node encryption

### PR DESCRIPTION
**Pull request by fdobrovolny**
Relates: https://github.com/SovereignCloudStack/issues/issues/675

### CODE REVIEW

**Review by artificial-intelligence — COMMENTED** [review]
generally LGTM, but I want to reread it a second time, as it's quite a long document, at the very least there are some spelling mistakes lurking in there imho, but I didn't want to comment on minor errors before actually having read the whole thing first.

Will provide more feedback, hopefully tomorrow.
Thanks for working on this!

**Review by matofeder — APPROVED** [review]
Overall it is an interesting reading and it looks good from my perspective. 

I left just some minor comments there.

**Comment by matofeder** [comment]
@OgarOgarovic check the failed pipelines

**Comment by matofeder** [comment]
> generally LGTM, but I want to reread it a second time, as it's quite a long document, at the very least there are some spelling mistakes lurking in there imho, but I didn't want to comment on minor errors before actually having read the whole thing first.
> 
> Will provide more feedback, hopefully tomorrow. Thanks for working on this!

@artificial-intelligence would you like to provide more feedback on this?

**Comment by matofeder** [comment]
@mbuechse @artificial-intelligence can we merge this one or do you have some further comments/discussion points?

**Comment by OgarOgarovic** [comment]
PR [here](https://github.com/SovereignCloudStack/standards/pull/805)

**Pull request merged**
