### PR TITLE
Issue/718 check for key manager

### PR DESCRIPTION
**Pull request by fraugabel**
changed the request method to check user role slightly to session-token based approach and added retry-option, if 401 occures for requesting specialized scope, also added a  small method to match different kinds of auth-urls with the valid path to request user roles from barbican

### CODE REVIEW

**Comment by fraugabel** [comment]
i will change that thanks

**Review by josephineSei — APPROVED** [review]

**Review by mbuechse — COMMENTED** [review]
The following observation is not directly related to this PR:

```shell
$ python3 -O Tests/iaas/key-manager/check-for-key-manager.py 
Auth plugin requires parameters which were not given: auth_url
Traceback (most recent call last):
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 119, in check_presence_of_key_manager
    connection = connect(cloud_name)
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 33, in connect
    return openstack.connect(
  File "/home/matthiasbuechse/.local/lib/python3.10/site-packages/openstack/__init__.py", line 98, in connect
    cloud_region = openstack.config.get_cloud_region(
  File "/home/matthiasbuechse/.local/lib/python3.10/site-packages/openstack/config/__init__.py", line 41, in get_cloud_region
    return config.get_one(options=parsed_options, **kwargs)
  File "/home/matthiasbuechse/.local/lib/python3.10/site-packages/openstack/config/loader.py", line 1270, in get_one
    auth_plugin = loader.load_from_options(**config['auth'])
  File "/home/matthiasbuechse/.local/lib/python3.10/site-packages/keystoneauth1/loading/base.py", line 160, in load_from_options
    raise exceptions.MissingRequiredOptions(missing_required)
keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 231, in <module>
    main()
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 227, in main
    return check_presence_of_key_manager(cloud)
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 123, in check_presence_of_key_manager
    raise Exception(
Exception: Connection to cloud 'None' was not successfully. The Catalog endpoint could not be accessed. Please check your cloud connection and authorization.
```

`assert` should NEVER be used in production! @josephineSei

**Review by mbuechse — COMMENTED** [review]
Next observation, this time related to this PR:

```shell
$ OS_CLOUD=gx-scs python3 Tests/iaas/key-manager/check-for-key-manager.py 
Key-Manager is present
Traceback (most recent call last):
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 231, in <module>
    main()
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 227, in main
    return check_presence_of_key_manager(cloud)
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 136, in check_presence_of_key_manager
    check_key_manager_permissions(connection, cloud_name)
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 154, in check_key_manager_permissions
    if not check_for_member_role(conn, cloud_name):
  File "/home/matthiasbuechse/opensrc/scs/standards/Tests/iaas/key-manager/check-for-key-manager.py", line 74, in check_for_member_role
    "domain": {"name": conn.auth["project_domain_name"]},
KeyError: 'project_domain_name'
```

**Review by mbuechse — COMMENTED** [review]
As expected, I was able to remove a whole lot of code by using the openstacksdk properly. Please make the following changes:

- do not use `print` (use logger instead, add option for debug logging, see other tests)
- do not use color codes
- do not use `assert` ever (except in unit tests)

**Comment by mbuechse** [comment]
One remark regading `print`: once we devised the formal test cases, we can and should use print for those; see item 3 in [this section of scs-0003-v1](https://docs.scs.community/standards/scs-0003-v1-sovereign-cloud-standards-yaml#basic-concepts)

**Comment by fraugabel** [comment]
> As expected, I was able to remove a whole lot of code by using the openstacksdk properly. 

the problem is that it gives me the `ERROR: ForbiddenException: 403: Client Error for url: https://(...)/secrets, Forbidden` on for instance our yaook os, where i could get a decent response before, that's why we used the former approach

**Comment by mbuechse** [comment]
> the problem is that it gives me the `ERROR: ForbiddenException: 403: Client Error for url: https://(...)/secrets, Forbidden` on for instance our yaook os, where i could get a decent response before, that's why we used the former approach

I would need the whole output to understand that.

I can imagine that this could be fixed by changing the clouds.yaml. Let's have a look on Monday.

**Comment by mbuechse** [comment]
I checked again, and it works better than what's in the main branch. However, the output is not usable. See [my comment for the other check](https://github.com/SovereignCloudStack/standards/pull/748#issuecomment-2437068840).

**Comment by mbuechse** [comment]
@fraugabel I reworked a few parts. I think it's usable now. However, before approving, I ask you to check yourself once more.

**Review by mbuechse — APPROVED** [review]

**Pull request merged**
