### PR TITLE
find recent Debian image even if only codenames are given

### LINKED ISSUE #696: [BUG] entropy-check taking hours
This happens on the syseleven environments. The test is terminated by Github after 6 hrs when it reaches the maximum runtime...

### PR DESCRIPTION
**Pull request by mbuechse**
resolves #696

### CODE REVIEW

**Review by gtema — APPROVED** [review]
Great would be to have a unittest for the function. I tried to iterate in the head with few common values and noticed that our famous "not_really_required" case of dashes or underscores instead of spaces will not work, "ubuntu22.04" neither. Not critical, but not sure about your general intention of the usage.

**Comment by mbuechse** [comment]
> Great would be to have a unittest for the function. I tried to iterate in the head with few common values and noticed that our famous "not_really_required" case of dashes or underscores instead of spaces will not work, "ubuntu22.04" neither. Not critical, but not sure about your general intention of the usage.

In this case, just make the test work better with the syseleven environments. But you are right, we need some better way of finding a certain image! I think this calls for better discoverability or at least more/better standardized properties?

**Comment by gtema** [comment]
Yes, there are standard properties os_distro and os_version We should make filling of those a standart and not the name convention

**Comment by mbuechse** [comment]
> Yes, there are standard properties `os_distro` and `os_version` We should make filling of those a standart and not the name convention

My bad! I have to say, I must have been blind. I should of course use those properties. I will make a new PR. Stupid me.

**Pull request merged**
