### PR TITLE
this document is not needed anymore since it is in the status page adr

### PR DESCRIPTION
**Pull request by fkr**
see https://github.com/SovereignCloudStack/standards/pull/191

### CODE REVIEW

**Review by itrich — APPROVED** [review]
LGTM.

**Comment by fkr** [comment]
What I actually just wondered: rm'ing this file (because it became part of the ADR) will cause links from issues to point to nowhere. Since those are issues that are closed (and as such, of no relevance any longer), I'm in the 'this is not a problem and I much rather have clean repos without cruft'-camp - but since we just had this discussion, I want to throw this up in the air.

@itrich @maxwolfs @garloff

**Comment by joshmue** [comment]
> If i am understanding your issue correctly you can simply adjust the links within those issues referencing the file from the specific commit at that time for correct history. Just choose the commit and browse to the file for copying the specific url.

Which of course can also be done at the time of writing an issue/comment. Not using permalinks to code/markdown files IMHO always risks to have broken links after some time (ignoring possibility of repository deletion etc.).

+1 for merging this PR, "this is not a problem and I much rather have clean repos without cruft" at least in this case.

**Comment by fkr** [comment]
paging @joshmue :) please review

**Review by joshmue — APPROVED** [review]
LGTM

**Pull request merged**
