### PR TITLE
Propose to stabilize default storage class scs-0211 by 2023-02-13.

### PR DESCRIPTION
**Pull request by garloff**
Signed-off-by: Kurt Garloff <kurt@garloff.de>

### CODE REVIEW

**Comment by garloff** [comment]
I added the label Work in Progress, which means this not should be merged prior to 2023-02-13 and probably another (possibly) discussion in the Container team.

**Comment by garloff** [comment]
And of course the target date should have read 2023-02-13.

**Comment by itrich** [comment]
/remind-me to stabilize this ADR on 2023-02-13

**Comment by joshmue** [comment]
Do not know why, but a link to K8s docs was broken. Fixed that in https://github.com/SovereignCloudStack/standards/pull/198/commits/f2b0ea971ff8dc0c69af7913b159fc1a5275396f.

**Review by joshmue — APPROVED** [review]

**Review by joshmue — APPROVED** [review]

**Comment by fkr** [comment]
Added to the Agenda of tomorrows IaaS call.

**Comment by garloff** [comment]
OK, I'm holding off with merging this one then until tomorrow's IaaS meet.

**Comment by garloff** [comment]
Agreement to stabilize this in the Container team meeting 2023-03-06.

**Pull request merged**
