### PR TITLE
Propose to stabilize the folder structure for standards.

### PR DESCRIPTION
**Pull request by garloff**
Signed-off-by: Kurt Garloff <kurt@garloff.de>

### CODE REVIEW

**Comment by garloff** [comment]
Marked as Work in Progress, please do not merge prior to 2023-02-06.

**Comment by itrich** [comment]
/remind-me to stabilize this ADR on 2023-02-06

**Comment by itrich** [comment]
Let's merge this after the Product Board call.

**Comment by garloff** [comment]
Hmmm, does this need further discussion?
I believe not, so IMVHO, we should merge it.
But we do need at least one approving review!

**Review by itrich — APPROVED** [review]

**Pull request merged**
