### PR TITLE
Propose to stabilize the new k8s version adoption std.

### PR DESCRIPTION
**Pull request by garloff**
Signed-off-by: Kurt Garloff <kurt@garloff.de>

### CODE REVIEW

**Comment by garloff** [comment]
Added Work in progress label; please don't merge prior to 2023-02-06.

**Review by batistein — APPROVED** [review]

**Review by joshmue — COMMENTED** [review]
# Nitpicking grammar

> In general the latest 3 minor version are maintained by the Kubernetes project.
> Every release will be maintained for about 14 months.
> First 12 month is standard support period.

could be:

> In general the latest 3 minor version**s** (<-) are maintained by the Kubernetes project.
> Every release will be maintained for about 14 months.
> First 12 month**s** (<-) **are the** (<-) standard support period.

# "Insured customers"

> This will allow customers **to be insured that their clusters are up to date** regarding security issues, bug fixes and new features when using SCS compliant clusters.

This sentence suggests that adopting new versions (at provider side) will take care of all running clusters, which is not necessarily the case. As IIRC discussed, this topic should be the handled in another standard/record.

Otherwise LGTM.

**Review by joshmue — APPROVED** [review]

**Comment by itrich** [comment]
/remind-me to stabilize this ADR on 2023-02-06.

**Comment by garloff** [comment]
> # Nitpicking grammar
> 
> > In general the latest 3 minor version are maintained by the Kubernetes project.
> > Every release will be maintained for about 14 months.
> > First 12 month is standard support period.
> 
> could be:
> 
> > In general the latest 3 minor version**s** (<-) are maintained by the Kubernetes project.
> > Every release will be maintained for about 14 months.
> > First 12 month**s** (<-) **are the** (<-) standard support period.

True. Want to open a PR?
Or should I do it?

> # "Insured customers"
> 
> > This will allow customers **to be insured that their clusters are up to date** regarding security issues, bug fixes and new features when using SCS compliant clusters.
> 
> This sentence suggests that adopting new versions (at provider side) will take care of all running clusters, which is not necessarily the case. As IIRC discussed, this topic should be the handled in another standard/record.

Suggestion:
This ensures that node images are available and can be upgraded to which are are up to date with respect to security issues, bug fixes and new features when using SCS compliant clusters.

(This clarifies that making the working/tested node images is responsibility of the provider and defined here. The responsibility about initiating rolling upgrades to existing clusters depends on the service model that we still have to define in another ADR.)


> Otherwise LGTM.

**Comment by garloff** [comment]
I fear we now need new reviews, @joshmue, @batistein, @ajfriesen, @jschoone.
Your support is very welcome!

**Comment by garloff** [comment]
/remind-me to stabilize this ADR on 2023-02-07.

**Review by joshmue — APPROVED** [review]

**Comment by ajfriesen** [comment]
I rephrased one one sentence a bit since it could be understood that we are also tackling node images here with the OS upgrade.
We are talking about kubernetes upgrades only in this ADR.
Also, node images were mentioned. It could be that provider do not use node images or have node images for initial provisioning but upgrades are handled differently.

Feel free to revert if that does not fit.

**Review by garloff — COMMENTED** [review]
Look goot to me.
I can not approve this unfortunately :-(

**Review by joshmue — APPROVED** [review]

**Pull request merged**
