### PR TITLE
Feat/add artcodix

### PR DESCRIPTION
**Pull request by garloff**
Note: We need a separate PR to also expose this on docs.scs.community/standards/

### CODE REVIEW

**Comment by garloff** [comment]
I believe the CI test is producing a false positive here ...

**Review by fkr — APPROVED** [review]

**Comment by garloff** [comment]
> I believe the CI test is producing a false positive here ...

That was wrong. There was a typo in my link to the badge, see #433.

**Comment by mbuechse** [comment]
@garloff it would have been nice to add artcodix to the zuul tests as well!

**Comment by garloff** [comment]
Let's do that in the next step.

**Pull request merged**
