### PR TITLE
Minor editorial improvements to K8s version policy standards scs-0210-v1 and scs-0210-v2

### PR DESCRIPTION
**Pull request by martinmo**
While working on #488 I noticed several shortcomings in the text of the version policy standards scs-0210-v1 and scs-0210-v2, which this PR intends to fix.

I've split the commits to make it easier to review (hopefully), because some of them tackle only cosmetic issues and improve link sharing between the documents by making use of reference style Markdown links.

Most importantly, this PR intends to resolve the following ambiguities:

- What do we mean exactly with a critical CVE?
- What do we mean exactly with a supported K8s version?
- What are CNCF E2E tests or where can I find them? (my understanding is: https://github.com/cncf/k8s-conformance)

Furthermore, the conformance test section was outdated or missing in both standard versions and I fixed this.

### CODE REVIEW

**Review by cah-hbaum — APPROVED** [review]
LGTM, nice updates!

**Comment by martinmo** [comment]
> Seems like minor editorial improvements, nothing to write home about ;)

Exactly =)

> Only one issue: You removed the parts about the now-obsolete test for v1. I think the sentence that this is now obsoleted (or rather **superseded**) by the new test is fine. But what about the old test? Did we remove it entirely?

Yes, I did in #488 and it was approved ;)

> I'm not sure that this was a good call. Well, if that's the case, then so be it. Out of curiosity: would it be very hard to add a v1-mode to the new test script?

If it is important, I would prefer to just restore the old script which also lived in a separate directory. And of course I would revert the changes wrt conformance testing in the scs-0210-v1 text.

**Comment by mbuechse** [comment]
> If it is important, I would prefer to just restore the old script which also lived in a separate directory. And of course I would revert the changes wrt conformance testing in the scs-0210-v1 text.

Maybe we restore it. We don't delete the standard, so let's also keep the test.

**Comment by martinmo** [comment]
> > If it is important, I would prefer to just restore the old script which also lived in a separate directory. And of course I would revert the changes wrt conformance testing in the scs-0210-v1 text.
> 
> Maybe we restore it. We don't delete the standard, so let's also keep the test.

I have created a separate PR #503 for restoring the test and reverted the change in scs-0210-v1 conformance test section here.

**Pull request merged**
