### PR TITLE
Add Tests/scs-compatible-kaas.yaml

### PR DESCRIPTION
**Pull request by mbuechse**

### CODE REVIEW

**Review by cah-hbaum — APPROVED** [review]
LGTM! (saw too late thats its only draft for now...)

**Comment by mbuechse** [comment]
@cah-hbaum @garloff I think I will remove the CNCF k8s conformance test for the time being because it's kind of complicated to set up and it runs for 2 h -- see here: <https://zuul.scs.community/t/SCS/build/b3a2d79f51994df599acf11085885f92/console>
I think we should discuss in the relevant meetings how to incorporate this test into the certification, maybe for v2.

**Comment by mbuechse** [comment]
@cah-hbaum To clear up a misunderstanding: this PR is not a draft PR, but the certificate scope is still in draft state (because it lacks `stabilized_on`). Still, this PR has to wait for #488 and #490 to make sense, so I might as well change it to a draft PR.

**Comment by cah-hbaum** [comment]
Just rerequest a review from me after its really done (should be possible).

**Review by martinmo — APPROVED** [review]
LGTM! But it needs a rebase or merge of `main` to actually be able to test it locally (because `k8s_version_policy.py` is missing in the branch).

Now only `stabilized_at` is missing =)

**Pull request merged**
