### PR TITLE
Feat/generator form

### PR DESCRIPTION
**Pull request by garloff**

### CODE REVIEW

**Comment by garloff** [comment]
The main missing piece is handling the dependent tables for CPUBrand gen and GPU gen.

**Comment by garloff** [comment]
Completes the work of #389.
Please review!

**Comment by garloff** [comment]
Review appreciated @berendt, @mbuechse or anyone else.

**Comment by berendt** [comment]
@garloff Latest state is usable via https://flavors.scs.community/cgi-bin/flavor-form.py ?

**Comment by garloff** [comment]
> @garloff Latest state is usable via https://flavors.scs.community/cgi-bin/flavor-form.py ?

Nope, that has the code from the main branch.
If you want to test, I can change the deployment to use the code from this branch ...
Alternatively, you can pass a `QUERY_STRING` parameter (in the environment, like cgi does it) or a flavor name as command line parameter for testing locally.

**Comment by garloff** [comment]
Use https://flavors.scs.community/cgi-bin/generator/flavor-form.py for testing.

**Comment by mbuechse** [comment]
I seem to have stumped it: https://flavors.scs.community/cgi-bin/generator/flavor-form.py?flavor=SCS-2V-8_GN

**Comment by garloff** [comment]
The 2 and a half broken cases are fixed now.
The combination of vendor and generation is a good idea, but it's a bit tedious to implement, as I generate the HTML forms from this input:
```
    pattrs = ("cpuvendor", "cpugen", "perf")
    pnames = (".CPU Vendor", "#.CPU Gen", "Performance")
    tbl_cpuvendor = {"i": "Intel", "z": "AMD", "a": "ARM", "r": "RISC-V"}
    tbl_cpuvendor_i_cpugen = {0: "Unspec/Pre-Skylake", 1: "Skylake", 2: "Cascade Lake", 3: "Ice Lake", 4: "Sapphire Rapids"}
    tbl_cpuvendor_z_cpugen = {0: "Unspec/Pre-Zen", 1: "Zen 1", 2: "Zen 2", 3: "Zen 3", 4: "Zen 4"}
    tbl_cpuvendor_a_cpugen = {0: "Unspec/Pre-A76", 1: "A76/NeoN1", 2: "A78/X1/NeoV1", 3: "A710/NeoN2"}
```
Obviously, it is possible for the code to recognize that there is a dependant table, so it can be done.

**Comment by garloff** [comment]
My suggestion is to merge as is and do any improvements in a follow up PR.

**Review by berendt — APPROVED** [review]

**Pull request merged**
