### PR TITLE
add ISSUE templates

### PR DESCRIPTION
**Pull request by fkr**
suggested by @mbuechse

### CODE REVIEW

**Comment by mbuechse** [comment]
Not sure if this is the right place to discuss the following: @fkr explained to me his scheme of adding labels to issues (one for the outcome, one for the track, yet others still that I currently don't recall, and lastly maybe "needs refinement"). I like this scheme, and I guess there might even be documentation that explains this already, but maybe we can even add a line about this to the templates, so whoever opens an issue is confronted with this information directly and can't miss it?

**Comment by fkr** [comment]
@mbuechse good suggestion. Am wondering wether really adding it to the templates helps or wether it makes sense, if we publish a blogpost and add some documentation on "how we work". 🤔

**Review by mbuechse — APPROVED** [review]
:100:

**Comment by fkr** [comment]
I opened an issue to follow up on this: https://github.com/SovereignCloudStack/issues/issues/332

**Pull request merged**
