### PR TITLE
Create certification-issuing-process.md

### PR DESCRIPTION
**Pull request by alexander-diab**
Hallo Eduard, 

started to sketch the process for certification as discussed a while ago. To be iterated and discussed in the next SIG meetings. 

I also would raise a question with respect to the check and issuing, which we might want to discuss: 
In a compliance check and certification issuing process. Do we have to capture and file, which infrastructure (e.g. by host names ) is specifically certified, i.e. where the script has been checked on standards?

### CODE REVIEW

**Comment by itrich** [comment]
We collected some ideas regarding the certification issuing process here: https://input.scs.community/scs-certification-issuing

# Regulations for getting SCS compatible certified:
As Operator, I want to achieve the Certificate SCS compatible.

1. SCS compatible certificates for the IaaS and KaaS layer MUST and CAN be achieved separately and WILL be labeled separately.


2. Every granted certificate „SCS compatible“ expires after the corresponding standard version of this layer has been obsoleted. For that matter any certification referring to a particular version of SCS standards does not have a duration of validity, but a fixed expiry date, regardless when the certification has been achieved.

3. For achieving the certificate „SCS compatible“ an operator MUST include the official SCS compliance test suite in his continuous test infrastructure -- for public clouds the recommended way to achieve this is to offer the SCS project access to the infrastructure so the test suite runs can be triggered continously by the SCS team and ensure continuous compliance. For non-public clouds, the results (log files) can be submitted to SCS by a mechanism of SCS' choice and need to be reproduced again on request by SCS.



4. The SCS certification assessment body (or entities empowered to do so) WILL review the certification application and either grant the certification, reject it or ask for further measures or information.


5. After having received a confirmation of a successful achievement of a certificate „SCS compatible“ granted by the SCS certification assessment body, the operator MAY use the „SCS compatible“ logo and publicly state the certified „SCS compatibility“  on the respective layer for the time of the validity of the certification, i.e. until the version of standards get obsoleted. The logos will contain a link to SCS owned pages that contain details on the achieved standards, either by embedding a hyperlink or a QR code for printed assets.

**Comment by itrich** [comment]
From my perspective, the documents needs to be restructured according to SCS-0001 and filled with the input we collected so far. Afterwards, we can leap the broader community into this discussions (and especially CSP that will need to adhere to this process).

**Comment by fkr** [comment]
> From my perspective, the documents needs to be restructured according to SCS-0001 and filled with the input we collected so far. Afterwards, we can leap the broader community into this discussions (and especially CSP that will need to adhere to this process).

I very much agree.

**Review by garloff — CHANGES_REQUESTED** [review]
The agreed on text in comment https://github.com/SovereignCloudStack/standards/pull/239/#issuecomment-1487444903 (document:
https://input.scs.community/scs-certification-issuing) should be used instead.
This was agreed in the 2023-03-16 meeting.
Please read carefully -- if you have questions, concerns, disagreements, please raise them -- it's important that we get this right.

**Comment by mbuechse** [comment]
@garloff @fkr @alexander-diab I tried to move this one forward a little bit according to the comments that I read. It is now also linked to an issue (#337).

**Comment by mbuechse** [comment]
Superseded by #356.

**Pull request closed without merging**
