### PR TITLE
Remove duplicated content and add overview of certified clouds

### PR DESCRIPTION
**Pull request by itrich**

### CODE REVIEW

**Comment by frosty-geek** [comment]
closes: #211

**Comment by itrich** [comment]
I added some more content. @garloff @fkr @maxwolfs This is ready to be reviewed.

**Review by fkr — DISMISSED** [review]
I like it. My recommendation would be to remove the 'Operational-Docs' section for now (instead of having it with the FIXME).

**Review by frosty-geek — APPROVED** [review]
LGTM

**Pull request merged**
