### PR TITLE
Add dNation Dev Project cloud resource

### PR DESCRIPTION
**Pull request by chess-knight**
Hello, I would like to ask you for a dev project for the team @SovereignCloudStack/dnation.
Thank you.

Signed-off-by: Roman Hros <roman.hros@dnation.cloud>

### CODE REVIEW

**Comment by frosty-geek** [comment]
Hi @chess-knight 
could you please provide your email address so I can create an openstack user for you. Who else from dNation needs an Account?

/cc @matofeder @mpilka

**Review by frosty-geek — APPROVED** [review]
Project created

**Comment by mpilka** [comment]
Hello Ralf,

thanks for your fast action, I am impressed.

> Hi @chess-knight Who else from dNation needs an Account?
> /cc @matofeder @mpilka

Yes, also for matofeder and mpilka please.

Thanks,
Martin

**Comment by frosty-geek** [comment]
I've created the other 2 accounts as well and "guessed" the email addresses. 

please contact me on matrix if you did not receive an email with the credentials...

Ralf

**Pull request merged**
